export PUBLIC_KEY="GDLLURLTBM6CNZAD7W6RPHHVMVLKAVV5PMC5KQRXVMCBN7NUDPIHR5GE"
export SECRET_KEY="SAGPZSLVWUFWNHSBVBFD5PXB57BGTASVQZUECPL6FFS7IRGPSTHQ4UDX"

export RPC_URL="http://localhost:8000/soroban/rpc"